import { Router } from 'express';
import { db } from '../db/index';
import { banksWallets } from '../db/schema';
import { eq } from 'drizzle-orm';
import { validate, bankWalletSchema } from '../validation';

const router = Router();

// Get all banks and wallets
router.get('/', async (req, res) => {
  try {
    const { entityId } = req.query;
    let query: any = db.select().from(banksWallets);
    
    if (entityId) {
      query = query.where(eq(banksWallets.entityId, entityId as string));
    }
    
    const allBanksWallets = await query;
    res.json(allBanksWallets);
  } catch (error) {
    console.error('Error fetching banks/wallets:', error);
    res.status(500).json({ error: 'Failed to fetch banks/wallets' });
  }
});

// Get bank/wallet by ID
router.get('/:id', async (req, res) => {
  try {
    const item = await db.select().from(banksWallets).where(eq(banksWallets.id, req.params.id));
    if (item.length === 0) {
      return res.status(404).json({ error: 'Bank/Wallet not found' });
    }
    res.json(item[0]);
  } catch (error) {
    console.error('Error fetching bank/wallet:', error);
    res.status(500).json({ error: 'Failed to fetch bank/wallet' });
  }
});

// Create new bank/wallet
router.post('/', validate(bankWalletSchema), async (req, res) => {
  try {
    // ID auto-generated by schema
    const itemData = { ...req.body };
    
    // Transform allowedCurrencies to currencies if needed
    if (itemData.allowedCurrencies && !itemData.currencies) {
      itemData.currencies = itemData.allowedCurrencies;
      delete itemData.allowedCurrencies;
    }
    
    // Transform status to isActive if needed
    if (itemData.status !== undefined && itemData.isActive === undefined) {
      itemData.isActive = itemData.status === "active" || itemData.status === true;
      delete itemData.status;
    }
    
    // Remove fields that don't exist in schema
    delete itemData.balances;
    delete itemData.lastTransaction;
    
    console.log('Creating bank/wallet with data:', itemData);
    const newItem = await db.insert(banksWallets).values(itemData).returning();
    res.status(201).json(newItem[0]);
  } catch (error: any) {
    console.error('Error creating bank/wallet:', error);
    console.error('Error details:', error.message, error.stack);
    res.status(500).json({ error: error.message || 'Failed to create bank/wallet' });
  }
});

// Update bank/wallet
router.put('/:id', async (req, res) => {
  try {
    const body = { ...req.body };
    
    // Transform allowedCurrencies to currencies if needed
    if (body.allowedCurrencies && !body.currencies) {
      body.currencies = body.allowedCurrencies;
      delete body.allowedCurrencies;
    }
    
    // Transform status to isActive if needed
    if (body.status !== undefined && body.isActive === undefined) {
      body.isActive = body.status === "active" || body.status === true;
      delete body.status;
    }
    
    // Remove fields that don't exist in schema
    delete body.balances;
    delete body.lastTransaction;
    
    console.log('Updating bank/wallet with data:', body);
    const updated = await db
      .update(banksWallets)
      .set({ ...body, updatedAt: new Date() })
      .where(eq(banksWallets.id, req.params.id))
      .returning();
    
    if (updated.length === 0) {
      return res.status(404).json({ error: 'Bank/Wallet not found' });
    }
    res.json(updated[0]);
  } catch (error: any) {
    console.error('Error updating bank/wallet:', error);
    console.error('Error details:', error.message, error.stack);
    res.status(500).json({ error: error.message || 'Failed to update bank/wallet' });
  }
});

// Delete bank/wallet
router.delete('/:id', async (req, res) => {
  try {
    const deleted = await db.delete(banksWallets).where(eq(banksWallets.id, req.params.id)).returning();
    if (deleted.length === 0) {
      return res.status(404).json({ error: 'Bank/Wallet not found' });
    }
    res.json({ message: 'Bank/Wallet deleted successfully' });
  } catch (error) {
    console.error('Error deleting bank/wallet:', error);
    res.status(500).json({ error: 'Failed to delete bank/wallet' });
  }
});

export default router;
