import { Router } from "express";
import { db } from "../db/index";
import { items } from "../db/schema";
import { eq, sql, desc } from "drizzle-orm";
import { validate, sanitizeObject } from "../validation";
import { z } from "zod";

// Zod schema for items
const itemSchema = z.object({
  id: z.string().optional(),
  entityId: z.string().min(1, "معرف الكيان مطلوب"),
  code: z.string().min(1, "كود الصنف مطلوب"),
  name: z.string().min(1, "اسم الصنف مطلوب").max(200),
  nameEn: z.string().nullable().optional(),
  barcode: z.string().nullable().optional(),
  categoryId: z.string().nullable().optional(),
  unitId: z.string().nullable().optional(),
  type: z.string().optional().default("stock"),
  purchasePrice: z.union([z.string(), z.number()]).optional(),
  salePrice: z.union([z.string(), z.number()]).optional(),
  minStock: z.union([z.string(), z.number()]).optional(),
  maxStock: z.union([z.string(), z.number()]).nullable().optional(),
  reorderPoint: z.union([z.string(), z.number()]).optional(),
  taxRate: z.union([z.string(), z.number()]).optional(),
  accountId: z.string().nullable().optional(),
  cogsAccountId: z.string().nullable().optional(),
  revenueAccountId: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  image: z.string().nullable().optional(),
  isActive: z.boolean().optional(),
});

const router = Router();

// Get all items with optional pagination
router.get("/", async (req, res) => {
  try {
    const { page, limit: qLimit } = req.query;

    if (page || qLimit) {
      const pageNum = Math.max(1, parseInt(page as string) || 1);
      const limitNum = Math.min(
        500,
        Math.max(1, parseInt(qLimit as string) || 100)
      );
      const offset = (pageNum - 1) * limitNum;

      const countResult = await db
        .select({ count: sql<number>`count(*)` })
        .from(items);
      const total = Number(countResult[0]?.count || 0);

      const data = await db
        .select()
        .from(items)
        .orderBy(desc(items.createdAt))
        .limit(limitNum)
        .offset(offset);

      return res.json({
        data,
        pagination: {
          page: pageNum,
          limit: limitNum,
          total,
          totalPages: Math.ceil(total / limitNum),
        },
      });
    }

    const allItems = await db.select().from(items);
    res.json(allItems);
  } catch (error) {
    console.error("Error fetching items:", error);
    res.status(500).json({ error: "Failed to fetch items" });
  }
});

// Get items by entity
router.get("/entity/:entityId", async (req, res) => {
  try {
    const entityItems = await db
      .select()
      .from(items)
      .where(eq(items.entityId, req.params.entityId));
    res.json(entityItems);
  } catch (error) {
    console.error("Error fetching items:", error);
    res.status(500).json({ error: "Failed to fetch items" });
  }
});

// Get item by ID
router.get("/:id", async (req, res) => {
  try {
    const item = await db
      .select()
      .from(items)
      .where(eq(items.id, req.params.id));
    if (item.length === 0) {
      return res.status(404).json({ error: "Item not found" });
    }
    res.json(item[0]);
  } catch (error) {
    console.error("Error fetching item:", error);
    res.status(500).json({ error: "Failed to fetch item" });
  }
});

// Create new item - ID auto-generated by schema
router.post("/", validate(itemSchema), async (req, res) => {
  try {
    const newItem = await db.insert(items).values(req.body).returning();
    res.status(201).json(newItem[0]);
  } catch (error) {
    console.error("Error creating item:", error);
    res.status(500).json({ error: "Failed to create item" });
  }
});

// Update item
router.put("/:id", async (req, res) => {
  try {
    const body = sanitizeObject(req.body);
    const updated = await db
      .update(items)
      .set({ ...body, updatedAt: new Date() })
      .where(eq(items.id, req.params.id))
      .returning();

    if (updated.length === 0) {
      return res.status(404).json({ error: "Item not found" });
    }
    res.json(updated[0]);
  } catch (error) {
    console.error("Error updating item:", error);
    res.status(500).json({ error: "Failed to update item" });
  }
});

// Delete item
router.delete("/:id", async (req, res) => {
  try {
    const deleted = await db
      .delete(items)
      .where(eq(items.id, req.params.id))
      .returning();
    if (deleted.length === 0) {
      return res.status(404).json({ error: "Item not found" });
    }
    res.json({ message: "Item deleted successfully" });
  } catch (error) {
    console.error("Error deleting item:", error);
    res.status(500).json({ error: "Failed to delete item" });
  }
});

export default router;
