import { Router } from "express";
import { db } from "../db/index";
import { warehouses } from "../db/schema";
import { eq, sql, desc } from "drizzle-orm";
import { validate, warehouseSchema } from "../validation";

const router = Router();

// Get all warehouses with optional pagination
router.get("/", async (req, res) => {
  try {
    const { page, limit: qLimit } = req.query;

    if (page || qLimit) {
      const pageNum = Math.max(1, parseInt(page as string) || 1);
      const limitNum = Math.min(
        200,
        Math.max(1, parseInt(qLimit as string) || 50)
      );
      const offset = (pageNum - 1) * limitNum;

      const countResult = await db
        .select({ count: sql<number>`count(*)` })
        .from(warehouses);
      const total = Number(countResult[0]?.count || 0);

      const data = await db
        .select()
        .from(warehouses)
        .orderBy(desc(warehouses.createdAt))
        .limit(limitNum)
        .offset(offset);

      return res.json({
        data,
        pagination: {
          page: pageNum,
          limit: limitNum,
          total,
          totalPages: Math.ceil(total / limitNum),
        },
      });
    }

    const allWarehouses = await db.select().from(warehouses);
    res.json(allWarehouses);
  } catch (error) {
    console.error("Error fetching warehouses:", error);
    res.status(500).json({ error: "Failed to fetch warehouses" });
  }
});

// Get warehouses by entity
router.get("/entity/:entityId", async (req, res) => {
  try {
    const entityWarehouses = await db
      .select()
      .from(warehouses)
      .where(eq(warehouses.entityId, req.params.entityId));
    res.json(entityWarehouses);
  } catch (error) {
    console.error("Error fetching warehouses:", error);
    res.status(500).json({ error: "Failed to fetch warehouses" });
  }
});

// Get warehouse by ID
router.get("/:id", async (req, res) => {
  try {
    const warehouse = await db
      .select()
      .from(warehouses)
      .where(eq(warehouses.id, req.params.id));
    if (warehouse.length === 0) {
      return res.status(404).json({ error: "Warehouse not found" });
    }
    res.json(warehouse[0]);
  } catch (error) {
    console.error("Error fetching warehouse:", error);
    res.status(500).json({ error: "Failed to fetch warehouse" });
  }
});

// Create new warehouse
router.post("/", validate(warehouseSchema), async (req, res) => {
  try {
    // ID auto-generated by schema
    const newWarehouse = await db
      .insert(warehouses)
      .values(req.body)
      .returning();
    res.status(201).json(newWarehouse[0]);
  } catch (error) {
    console.error("Error creating warehouse:", error);
    res.status(500).json({ error: "Failed to create warehouse" });
  }
});

// Update warehouse
router.put("/:id", async (req, res) => {
  try {
    // Clean up body - remove fields that shouldn't be updated directly
    const {
      id: _id,
      createdAt: _createdAt,
      updatedAt: _updatedAt,
      itemsCount: _itemsCount,
      totalValue: _totalValue,
      ...updateData
    } = req.body;
    const updated = await db
      .update(warehouses)
      .set({ ...updateData, updatedAt: new Date() })
      .where(eq(warehouses.id, req.params.id))
      .returning();

    if (updated.length === 0) {
      return res.status(404).json({ error: "Warehouse not found" });
    }
    res.json(updated[0]);
  } catch (error) {
    console.error("Error updating warehouse:", error);
    res.status(500).json({ error: "Failed to update warehouse" });
  }
});

// Delete warehouse
router.delete("/:id", async (req, res) => {
  try {
    const deleted = await db
      .delete(warehouses)
      .where(eq(warehouses.id, req.params.id))
      .returning();
    if (deleted.length === 0) {
      return res.status(404).json({ error: "Warehouse not found" });
    }
    res.json({ message: "Warehouse deleted successfully" });
  } catch (error) {
    console.error("Error deleting warehouse:", error);
    res.status(500).json({ error: "Failed to delete warehouse" });
  }
});

export default router;
